blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/cobwebsh/BepInEx/discussions
    about: "Not an issue or a bug report? Talk freely about BepInHecks features and issues here without a template."
  - name: Cobweb Discord
    url: https://discord.gg/m4244VbvHA
    about: "Talk about mod development and report smaller issues here. You'll most likely get faster support on Discord."
